[project]
id = "regex"
version = "0.2.0"
mach = "^6"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.linux-aarch64]
isa = "aarch64"
os  = "linux"
abi = "aapcs64"

[target.windows-x86_64]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin-x86_64]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[target.darwin-aarch64]
isa = "aarch64"
os  = "darwin"
abi = "aapcs64"

# the library. as the default, its entry is what a dependent's `use regex;` binds
[artifact.regex]
kind = "static"
default = true
entry = "lib/regex.mach"
out = "lib/regex"
targets = ["*"]
link = []
need = []

# a rebar runner, for benchmarking against other engines with rebar
[artifact.rebar]
kind = "bin"
entry = "bin/rebar.mach"
out = "bin/rebar{artifact.suffix}"
targets = ["*"]
link = ["kernel32"]
need = []

[link.kernel32]
source = "system"
name = "kernel32.dll"
os = ["windows"]
isa = ["*"]
abi = ["*"]
export = false

[profile.debug]
default = true
opt = 0
debug = true
simd = "scalarize"
vectorize = false
float_reassoc = false

[profile.release]
opt = 2
debug = false
simd = "scalarize"
vectorize = true
float_reassoc = false

[dep.std]
git = "https://github.com/briar-systems/mach-std"
version = "^9.0"
